### ISSUE TITLE
External dev contributions.

### ISSUE THREAD

**Issue by itsMarcoSolis** [tangramproject/tangram#4]
Hello there!

I hope you're doing well. I wanted to express my intent to contribute to the development of Tangram.

To kick things off smoothly, it would be immensely helpful if we could collaboratively outline the required features, bug fixes, and documentation enhancements that would benefit the project. I'm willing to take the lead on maintaining this list, be it as a separate GitHub issue, a GitHub Project board, or any other preferred format.

I understand that @Pingpong has invaluable insight into the project's current state. @PingPong, if you could provide some high-level ideas or thoughts, I'd be more than happy to delve into the details, conduct investigations, and refine these requirements. This way, myself or other contributors can take the initiative to begin working on them.

I'm open to any thoughts, feedback, or initial tasks you might have in mind.

Looking forward to your response and the opportunity to contribute!

P.S. Apologies for not tagging PP; it seems that the tagging feature is currently not functioning on my end.

**Comment by The-Jaxx** [comment]
Hi,

Nice to see you're willing to help and i hope @pingpong will contact you, i bet he can help with the info you're looking for.
Communication with him is a bit hard sometimes though, so i suggest maybe asking this on the discord, hope more people can help you there.

**Comment by itsMarcoSolis** [comment]
No response, closing the issue.
